// Task Statistics Action constants
export const GET_STATISTICS = 'GET_STATISTICS';
export const GET_STATISTICS_SUCCESS = 'GET_STATISTICS_SUCCESS';
export const GET_STATISTICS_ERROR = 'GET_STATISTICS_ERROR';
